// Style reminder: Archivo editorial cívico — admin is a transparent control room, clearly labeled as demo protection.

import { Activity, BookOpen, BrainCircuit, Check, Download, FileJson, Gauge, HardDrive, KeyRound, RefreshCw, Search, Settings2, Upload, Volume2, Wifi, Wrench } from "lucide-react";
import { useRef, useState } from "react";
import { Link } from "wouter";
import { AppShell } from "@/components/AppShell";
import { courses } from "@/content/courses";
import { DEFAULT_CONFIG, DEFAULT_SYSTEM_PROMPT } from "@/lib/config";
import { useAgent } from "@/contexts/AgentContext";

const tabs = [["overview", "Overview", Gauge], ["models", "Models", BrainCircuit], ["behavior", "Behavior", Settings2], ["tools", "Tools", Wrench], ["knowledge", "Knowledge", BookOpen], ["runtime", "Runtime", Activity]] as const;

export default function Admin() {
  const { config, setConfig, runtime, modelStatus, modelProgress, preloadLLM, clearMemory } = useAgent();
  const [tab, setTab] = useState<(typeof tabs)[number][0]>("overview");
  const importRef = useRef<HTMLInputElement>(null);
  const update = (patch: any) => setConfig({ ...config, ...patch });
  const downloadConfig = () => { const blob = new Blob([JSON.stringify(config, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "page-agent-config.json"; link.click(); URL.revokeObjectURL(url); };
  const importConfig = (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { try { const parsed = JSON.parse(String(reader.result)); setConfig({ ...DEFAULT_CONFIG, ...parsed }); } catch { /* ignore invalid demo import */ } }; reader.readAsText(file); };
  return <AppShell admin><div className="admin-layout"><aside className="admin-sidebar"><div className="admin-brand"><span className="status-dot" data-state="ready" />Page Agent <small>Harness / Admin</small></div><div className="admin-demo-note"><KeyRound size={15} /><span>Protección de demostración<br /><strong>no es autenticación segura</strong></span></div><nav>{tabs.map(([id, label, Icon]) => <button key={id} className={tab === id ? "is-active" : ""} onClick={() => setTab(id)}><Icon size={16} />{label}</button>)}</nav><Link href="/" className="admin-back">← Volver a la página</Link></aside><main className="admin-main"><div className="admin-topline"><div><span className="eyebrow dark-eyebrow">Owner console / 06</span><h1>{tabs.find((item) => item[0] === tab)?.[1]}</h1></div><div className="admin-top-actions"><button className="outline-button" onClick={downloadConfig}><Download size={15} /> Exportar</button><button className="outline-button" onClick={() => importRef.current?.click()}><Upload size={15} /> Importar</button><input ref={importRef} type="file" accept="application/json" hidden onChange={importConfig} /></div></div>{tab === "overview" && <Overview runtime={runtime} modelStatus={modelStatus} modelProgress={modelProgress} config={config} preloadLLM={preloadLLM} />}{tab === "models" && <Models config={config} update={update} modelStatus={modelStatus} modelProgress={modelProgress} preloadLLM={preloadLLM} />}{tab === "behavior" && <Behavior config={config} update={update} />}{tab === "tools" && <Tools config={config} update={update} />}{tab === "knowledge" && <Knowledge config={config} />}{tab === "runtime" && <RuntimePanel runtime={runtime} config={config} clearMemory={clearMemory} />}</main></div></AppShell>;
}

function Panel({ title, eyebrow, children }: { title: string; eyebrow?: string; children: React.ReactNode }) { return <section className="admin-panel"><div className="panel-heading"><div>{eyebrow && <span className="eyebrow dark-eyebrow">{eyebrow}</span>}<h2>{title}</h2></div></div>{children}</section>; }

function Overview({ runtime, modelStatus, modelProgress, config, preloadLLM }: any) { return <div className="admin-grid"><Panel title="Estado del harness" eyebrow="01 / overview"><div className="health-grid"><div><span className="health-value">{runtime?.backend ?? "—"}</span><span>backend activo</span></div><div><span className="health-value">{modelStatus === "ready" ? "Ready" : "Idle"}</span><span>modelo LLM</span></div><div><span className="health-value">{courses.length}</span><span>cursos indexados</span></div><div><span className="health-value">{runtime?.indexedDb ? "Sí" : "No"}</span><span>IndexedDB</span></div></div><div className="model-progress"><div><span>Preparación del modelo</span><strong>{modelStatus === "downloading" ? `${modelProgress}%` : modelStatus === "ready" ? "Listo" : "Bajo demanda"}</strong></div><div className="progress-track"><span style={{ width: `${modelStatus === "ready" ? 100 : modelStatus === "downloading" ? modelProgress : 0}%` }} /></div><button className="primary-button" onClick={preloadLLM}><BrainCircuit size={15} /> Cargar modelo local</button></div></Panel><Panel title="Qué está funcionando" eyebrow="02 / signals"><div className="signals-list"><Signal label="RAG lexical local" value="Activo" /><Signal label="Artifacts reversibles" value="Activo" /><Signal label="Prompt grounding" value="Activo" /><Signal label="Inferencia remota" value="Deshabilitada" danger /></div></Panel><Panel title="Configuración actual" eyebrow="03 / snapshot"><div className="config-summary"><span><strong>LLM</strong>{config.models.llm.modelId}</span><span><strong>Embeddings</strong>{config.models.embeddings.modelId}</span><span><strong>Memoria</strong>{config.memory.mode} · {config.memory.maxTurns} turnos</span><span><strong>Snapshot</strong>13 agosto 2026</span></div></Panel></div>; }
function Signal({ label, value, danger = false }: { label: string; value: string; danger?: boolean }) { return <div><span className="status-dot" data-state={danger ? "error" : "ready"} /><span>{label}</span><strong className={danger ? "is-danger" : ""}>{value}</strong></div>; }
function Models({ config, update, modelStatus, modelProgress, preloadLLM }: any) { return <div className="admin-grid"><Panel title="LLM / text generation" eyebrow="Model configuration"><div className="form-grid"><label>Model ID<input value={config.models.llm.modelId} onChange={(event) => update({ models: { ...config.models, llm: { ...config.models.llm, modelId: event.target.value } } })} /></label><label>Dtype<select value={config.models.llm.dtype} onChange={(event) => update({ models: { ...config.models, llm: { ...config.models.llm, dtype: event.target.value } } })}><option value="q4">q4 · browser friendly</option><option value="q8">q8 · balanced</option><option value="fp16">fp16 · WebGPU</option></select></label><label>Device<select value={config.models.llm.device} onChange={(event) => update({ models: { ...config.models, llm: { ...config.models.llm, device: event.target.value } } })}><option value="webgpu">WebGPU → fallback WASM</option><option value="wasm">WASM / CPU</option></select></label><label>Max new tokens<input type="number" value={config.models.llm.maxNewTokens} onChange={(event) => update({ models: { ...config.models, llm: { ...config.models.llm, maxNewTokens: Number(event.target.value) } } })} /></label></div><div className="model-actions"><button className="primary-button" onClick={preloadLLM}><Download size={15} /> {modelStatus === "downloading" ? `Descargando ${modelProgress}%` : "Descargar / cargar"}</button><button className="outline-button"><RefreshCw size={15} /> Probar</button></div></Panel><Panel title="Embeddings / retrieval" eyebrow="Semantic layer"><div className="config-summary"><span><strong>Model ID</strong>{config.models.embeddings.modelId}</span><span><strong>Pooling</strong>{config.models.embeddings.pooling} · normalizado</span><span><strong>Top K</strong>{config.retrieval.topK}</span><span><strong>Current page boost</strong>{config.retrieval.currentPageBoost}</span></div></Panel><Panel title="Voice stack" eyebrow="ASR + TTS"><div className="config-summary"><span><strong>ASR</strong>{config.models.asr.modelId} · {config.models.asr.language}</span><span><strong>TTS</strong>{config.models.tts.engine} · fallback del navegador</span></div></Panel></div>; }
function Behavior({ config, update }: any) { return <div className="admin-grid"><Panel title="System prompt" eyebrow="Grounding policy"><textarea className="prompt-editor" value={config.prompt.system} onChange={(event) => update({ prompt: { ...config.prompt, system: event.target.value } })} /><div className="model-actions"><button className="primary-button" onClick={() => update({ prompt: { ...config.prompt, system: DEFAULT_SYSTEM_PROMPT } })}>Restaurar default</button><span className="saved-note"><Check size={14} /> Se guarda en localStorage al editar</span></div></Panel><Panel title="Memory policy" eyebrow="Local-only memory"><div className="form-grid"><label>Mode<select value={config.memory.mode} onChange={(event) => update({ memory: { ...config.memory, mode: event.target.value } })}><option value="none">none · sin historial</option><option value="session">session · pestaña actual</option><option value="persistent">persistent · IndexedDB</option></select></label><label>Max turns<input type="number" value={config.memory.maxTurns} onChange={(event) => update({ memory: { ...config.memory, maxTurns: Number(event.target.value) } })} /></label></div></Panel></div>; }
function Tools({ config, update }: any) { return <Panel title="Tool registry" eyebrow="Allow-listed actions"><div className="tool-list">{Object.entries(config.tools).map(([key, enabled]) => <label key={key}><span><Wrench size={15} /><strong>{key}</strong><small>Acción determinista, validada y local</small></span><input type="checkbox" checked={Boolean(enabled)} onChange={(event) => update({ tools: { ...config.tools, [key]: event.target.checked } })} /></label>)}</div></Panel>; }
function Knowledge({ config }: any) { return <div className="admin-grid"><Panel title="Knowledge snapshot" eyebrow="Local RAG index"><div className="health-grid"><div><span className="health-value">1</span><span>página base</span></div><div><span className="health-value">{courses.length}</span><span>cursos</span></div><div><span className="health-value">{courses.length * 3 + 4}</span><span>chunks estructurados</span></div><div><span className="health-value">{config.retrieval.topK}</span><span>top K</span></div></div><div className="debug-search"><label>Query de depuración<input defaultValue="curso para aprender LLM" /></label><button className="outline-button"><SearchIcon /> Ejecutar retrieval</button></div></Panel><Panel title="Retrieval controls" eyebrow="Tune locally"><div className="form-grid"><label>Chunk size<input type="number" defaultValue={config.retrieval.chunkSize} /></label><label>Overlap<input type="number" defaultValue={config.retrieval.overlap} /></label><label>Similarity threshold<input type="number" step="0.01" defaultValue={config.retrieval.similarityThreshold} /></label><label>Current-page boost<input type="number" step="0.01" defaultValue={config.retrieval.currentPageBoost} /></label></div></Panel></div>; }
function SearchIcon() { return <Search size={15} />; }
function RuntimePanel({ runtime, config, clearMemory }: any) { const checks = [["WebGPU", runtime?.webgpu ? "available" : "unavailable", Wifi], ["WASM", runtime?.wasm ? "available" : "unavailable", CpuIcon], ["Cache API", runtime?.cacheStorage ? "available" : "unavailable", HardDrive], ["IndexedDB", runtime?.indexedDb ? "available" : "unavailable", DatabaseIcon], ["Microphone", runtime?.microphone ?? "unknown", Volume2], ["Service Worker", runtime?.serviceWorker ?? "unknown", Activity]] as const; return <div className="admin-grid"><Panel title="Capability detector" eyebrow="Runtime / device"><div className="runtime-checks">{checks.map(([label, value, Icon]) => <div key={label}><Icon size={16} /><span>{label}</span><strong className={value === "unavailable" || value === "denied" ? "is-danger" : ""}>{value}</strong></div>)}</div></Panel><Panel title="Local resource policy" eyebrow="Model manager"><div className="config-summary"><span><strong>LLM</strong>{config.models.llm.modelId}</span><span><strong>Backend</strong>{runtime?.backend}</span><span><strong>Remote inference</strong>nunca</span><span><strong>Modelo cache</strong>Cache Storage / browser</span></div><button className="outline-button" onClick={clearMemory}><HardDrive size={15} /> Borrar memoria local</button></Panel></div>; }
function CpuIcon(props: any) { return <Gauge {...props} />; }
function DatabaseIcon(props: any) { return <HardDrive {...props} />; }
