// Style reminder: Archivo editorial cívico — course data is the factual spine behind every artifact.

import type { ContextChunk, Course, CurriculumModule } from "@/lib/types";

export const courses: Course[] = [
  {
    id: "machine-learning",
    slug: "machine-learning",
    sourceUrl: "https://dcc.uchile.cl/educacion-continua/",
    title: "Machine Learning",
    code: "DCC-ML-01",
    category: "Inteligencia Artificial",
    program: "Cursos de especialización",
    duration: "24 horas · 8 sesiones",
    price: "$420.000 CLP",
    startDate: "24 de agosto de 2026",
    modality: "Online · clases en vivo",
    objectives: ["Comprender los fundamentos del aprendizaje supervisado y no supervisado.", "Construir y evaluar modelos predictivos con Python.", "Interpretar métricas y decisiones de modelamiento."],
    contents: ["Preparación de datos", "Regresión y clasificación", "Árboles y ensambles", "Validación y métricas", "Proyecto aplicado"],
    professors: ["Equipo académico DCC"],
    requirements: ["Programación básica en Python", "Álgebra y estadística introductoria"],
    payment: ["Pago online", "Consulta facilidades directamente con Educación Continua"],
    relatedCourseIds: ["deep-learning", "python-data", "generative-ai"],
    shortDescription: "Una entrada práctica al modelamiento predictivo, desde los datos hasta la evaluación.",
    accent: "maroon",
  },
  {
    id: "deep-learning",
    slug: "redes-neuronales-deep-learning",
    sourceUrl: "https://dcc.uchile.cl/educacion-continua/",
    title: "Redes Neuronales y Deep Learning",
    code: "DCC-DL-02",
    category: "Inteligencia Artificial",
    program: "Cursos de especialización",
    duration: "30 horas · 10 sesiones",
    price: "$520.000 CLP",
    startDate: "5 de octubre de 2026",
    modality: "Online · clases en vivo",
    objectives: ["Explicar la arquitectura y el entrenamiento de redes neuronales.", "Aplicar modelos profundos a problemas de imágenes y texto.", "Diseñar experimentos reproducibles."],
    contents: ["Perceptrón y backpropagation", "Redes convolucionales", "Representaciones y embeddings", "Regularización", "Proyecto de deep learning"],
    professors: ["Equipo académico DCC"],
    requirements: ["Programación en Python", "Fundamentos de Machine Learning"],
    payment: ["Pago online", "Consulta facilidades directamente con Educación Continua"],
    relatedCourseIds: ["machine-learning", "nlp", "generative-ai"],
    shortDescription: "Arquitecturas profundas para quienes ya dominan los conceptos base de Machine Learning.",
    accent: "teal",
  },
  {
    id: "generative-ai",
    slug: "inteligencia-artificial-generativa",
    sourceUrl: "https://dcc.uchile.cl/educacion-continua/",
    title: "Inteligencia Artificial Generativa",
    code: "DCC-GEN-03",
    category: "Inteligencia Artificial",
    program: "Cursos de especialización",
    duration: "20 horas · 6 sesiones",
    price: "$390.000 CLP",
    startDate: "16 de noviembre de 2026",
    modality: "Online · clases en vivo",
    objectives: ["Distinguir familias de modelos generativos y sus usos.", "Diseñar flujos de trabajo con modelos de lenguaje.", "Evaluar riesgos, límites y trazabilidad."],
    contents: ["Modelos de lenguaje", "Prompting y evaluación", "RAG y grounding", "Agentes y herramientas", "Uso responsable"],
    professors: ["Equipo académico DCC"],
    requirements: ["Experiencia general con herramientas digitales", "No requiere experiencia previa en IA"],
    payment: ["Pago online", "Consulta facilidades directamente con Educación Continua"],
    relatedCourseIds: ["machine-learning", "nlp", "python-data"],
    shortDescription: "Un recorrido aplicado por modelos generativos, evaluación y sistemas fundamentados.",
    accent: "ochre",
  },
  {
    id: "nlp",
    slug: "procesamiento-lenguaje-natural",
    sourceUrl: "https://dcc.uchile.cl/educacion-continua/",
    title: "Procesamiento de Lenguaje Natural",
    code: "DCC-NLP-04",
    category: "Datos e IA",
    program: "Cursos de especialización",
    duration: "24 horas · 8 sesiones",
    price: "$430.000 CLP",
    startDate: "7 de septiembre de 2026",
    modality: "Online · clases en vivo",
    objectives: ["Representar texto para tareas de análisis computacional.", "Construir clasificadores y buscadores semánticos.", "Comprender el papel de los embeddings."],
    contents: ["Preprocesamiento", "Embeddings", "Clasificación de texto", "Búsqueda semántica", "Modelos de lenguaje"],
    professors: ["Equipo académico DCC"],
    requirements: ["Programación básica en Python", "Interés en análisis de texto"],
    payment: ["Pago online", "Consulta facilidades directamente con Educación Continua"],
    relatedCourseIds: ["generative-ai", "python-data", "deep-learning"],
    shortDescription: "Del texto crudo a representaciones y sistemas que pueden buscar, clasificar y explicar.",
    accent: "teal",
  },
  {
    id: "python-data",
    slug: "python-aplicado-ciencia-datos",
    sourceUrl: "https://dcc.uchile.cl/educacion-continua/",
    title: "Python aplicado a la Ciencia de Datos",
    code: "DCC-PY-05",
    category: "Programación y datos",
    program: "Diploma de Desarrollo Profesional en Python aplicado a la Ciencia de Datos",
    duration: "36 horas · 12 sesiones",
    price: "$560.000 CLP",
    startDate: "17 de agosto de 2026",
    modality: "Online · clases en vivo",
    objectives: ["Resolver tareas de análisis con Python.", "Trabajar con estructuras de datos y visualización.", "Preparar un flujo reproducible de análisis."],
    contents: ["Python y notebooks", "Pandas", "Visualización", "Limpieza de datos", "Proyecto aplicado"],
    professors: ["Equipo académico DCC"],
    requirements: ["No requiere experiencia avanzada", "Se recomienda familiaridad con operaciones básicas de computador"],
    payment: ["Pago online", "Consulta facilidades directamente con Educación Continua"],
    relatedCourseIds: ["machine-learning", "nlp", "software-engineering"],
    shortDescription: "Una base aplicada para transformar datos en análisis reproducibles con Python.",
    accent: "ochre",
  },
  {
    id: "software-engineering",
    slug: "ingenieria-de-software",
    sourceUrl: "https://dcc.uchile.cl/educacion-continua/",
    title: "Ingeniería de Software",
    code: "DCC-SW-06",
    category: "Ingeniería de software",
    program: "Diploma de Postítulo en Ingeniería de Software",
    duration: "32 horas · 10 sesiones",
    price: "$480.000 CLP",
    startDate: "31 de agosto de 2026",
    modality: "Online · clases en vivo",
    objectives: ["Diseñar software mantenible y colaborativo.", "Conectar requisitos, arquitectura y calidad.", "Aplicar prácticas de entrega continua."],
    contents: ["Requisitos", "Arquitectura", "Testing", "Integración continua", "Trabajo de equipos"],
    professors: ["Equipo académico DCC"],
    requirements: ["Experiencia básica en desarrollo de software"],
    payment: ["Pago online", "Consulta facilidades directamente con Educación Continua"],
    relatedCourseIds: ["project-management", "python-data"],
    shortDescription: "Prácticas para diseñar, construir y mantener software que pueda crecer con el equipo.",
    accent: "charcoal",
  },
  {
    id: "project-management",
    slug: "gestion-proyectos-informaticos",
    sourceUrl: "https://dcc.uchile.cl/educacion-continua/",
    title: "Gestión de Proyectos Informáticos",
    code: "DCC-PM-07",
    category: "Gestión tecnológica",
    program: "Diploma de Postítulo en Gestión de Proyectos Informáticos",
    duration: "28 horas · 9 sesiones",
    price: "$450.000 CLP",
    startDate: "14 de septiembre de 2026",
    modality: "Online · clases en vivo",
    objectives: ["Planificar proyectos tecnológicos con criterios claros.", "Gestionar riesgos, equipos y entregables.", "Comunicar decisiones a distintos actores."],
    contents: ["Alcance y planificación", "Riesgos", "Equipos", "Métricas", "Cierre y aprendizaje"],
    professors: ["Equipo académico DCC"],
    requirements: ["Experiencia laboral o académica en proyectos"],
    payment: ["Pago online", "Consulta facilidades directamente con Educación Continua"],
    relatedCourseIds: ["software-engineering", "python-data"],
    shortDescription: "Una mirada práctica para conducir proyectos digitales con trazabilidad y foco.",
    accent: "maroon",
  },
  {
    id: "frontend-bootcamp",
    slug: "bootcamp-desarrollo-frontend",
    sourceUrl: "https://dcc.uchile.cl/educacion-continua/",
    title: "Bootcamp Desarrollo Frontend",
    code: "DCC-BOOT-08",
    category: "Bootcamps",
    program: "Bootcamps Educación Continua DCC",
    duration: "80 horas · formato intensivo",
    price: "Consultar convocatoria",
    startDate: "Convocatoria por confirmar",
    modality: "Online · clases en vivo",
    objectives: ["Construir interfaces web responsivas.", "Trabajar con componentes y estado.", "Publicar un proyecto demostrable."],
    contents: ["HTML y CSS", "JavaScript", "Componentes", "Accesibilidad", "Proyecto final"],
    professors: ["Equipo académico DCC"],
    requirements: ["Motivación y disponibilidad para un formato intensivo"],
    payment: ["Consultar convocatoria vigente"],
    relatedCourseIds: ["software-engineering", "python-data"],
    shortDescription: "Un trayecto intensivo para pasar de la idea a una interfaz web funcional.",
    accent: "charcoal",
  },
];

export const courseById = Object.fromEntries(courses.map((course) => [course.id, course])) as Record<string, Course>;

const stageByIndex: CurriculumModule["stage"][] = ["base", "core", "core", "applied", "capstone"];

export const curriculumByCourse = Object.fromEntries(courses.map((course) => {
  const totalHours = Number(course.duration.match(/\d+/)?.[0] ?? 20);
  const moduleHours = Math.max(2, Math.round(totalHours / Math.max(1, course.contents.length)));
  const modules = course.contents.map((title, index): CurriculumModule => ({
    id: `${course.id}-module-${index + 1}`,
    title,
    stage: stageByIndex[Math.min(index, stageByIndex.length - 1)],
    sequence: index + 1,
    hours: index === course.contents.length - 1 ? Math.max(2, totalHours - moduleHours * (course.contents.length - 1)) : moduleHours,
    prerequisites: index === 0 ? course.requirements : [`${course.id}-module-${index}`],
  }));
  return [course.id, modules];
})) as Record<string, CurriculumModule[]>;

export const courseChunks: ContextChunk[] = courses.flatMap((course) => [
  {
    id: `course:${course.id}:overview`,
    route: `/cursos/${course.slug}`,
    entityType: "course",
    entityId: course.id,
    heading: course.title,
    text: `${course.title}. ${course.shortDescription} Categoría: ${course.category}. Programa: ${course.program}. Modalidad: ${course.modality}. Duración: ${course.duration}. Precio: ${course.price}. Inicio: ${course.startDate}.`,
    selector: `[data-course-id="${course.id}"]`,
    source: "structured-content",
  },
  {
    id: `course:${course.id}:objectives`,
    route: `/cursos/${course.slug}`,
    entityType: "course",
    entityId: course.id,
    heading: `Objetivos · ${course.title}`,
    text: course.objectives.join(" "),
    selector: `#${course.id}-objectives`,
    source: "structured-content",
  },
  {
    id: `course:${course.id}:contents`,
    route: `/cursos/${course.slug}`,
    entityType: "course",
    entityId: course.id,
    heading: `Contenidos · ${course.title}`,
    text: course.contents.join(". "),
    selector: `#${course.id}-contents`,
    source: "structured-content",
  },
  {
    id: `course:${course.id}:curriculum`,
    route: `/cursos/${course.slug}`,
    entityType: "course",
    entityId: course.id,
    heading: `Malla y precedencias · ${course.title}`,
    text: curriculumByCourse[course.id].map((module) => `${module.sequence}. ${module.title}. Etapa: ${module.stage}. ${module.prerequisites.length ? `Prerequisitos: ${module.prerequisites.join(", ")}.` : "Sin prerequisitos."}`).join(" "),
    selector: `#${course.id}-curriculum`,
    source: "structured-content",
  },
]);
